# Generated by Django 4.0.2 on 2023-01-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
    ]
